import { getSpellSheetDetail } from "./spellSheetDetails.js";

const valueLabels = {
  Strength: "Fuerza",
  Dexterity: "Destreza",
  Constitution: "Constitucion",
  Intelligence: "Inteligencia",
  Wisdom: "Sabiduria",
  Charisma: "Carisma",
  strength: "Fuerza",
  dexterity: "Destreza",
  constitution: "Constitucion",
  intelligence: "Inteligencia",
  wisdom: "Sabiduria",
  charisma: "Carisma",
  "Strength or Dexterity": "Fuerza o Destreza",
  Martial: "Marcial",
  "Arcane Caster": "Lanzador arcano",
  "Divine Caster": "Lanzador divino",
  "Primal Caster": "Lanzador primal",
  "Expert Martial": "Experto marcial",
  "Pact Caster": "Lanzador de pacto",
  "Arcane Half Caster": "Medio lanzador arcano",
  Fighter: "Guerrero",
  Wizard: "Mago",
  Cleric: "Clerigo",
  Barbarian: "Barbaro",
  Bard: "Bardo",
  Druid: "Druida",
  Monk: "Monje",
  Paladin: "Paladin",
  Ranger: "Ranger",
  Rogue: "Picaro",
  Sorcerer: "Hechicero",
  Warlock: "Brujo",
  Artificer: "Artifice",
  Champion: "Campeon",
  Evoker: "Evocador",
  "Life Domain": "Dominio de vida",
  "Light Domain": "Dominio de luz",
  "Trickery Domain": "Dominio del engano",
  "War Domain": "Dominio de guerra",
  "Path of the Berserker": "Senda del berserker",
  "Path of the Wild Heart": "Senda del corazon salvaje",
  "Path of the World Tree": "Senda del arbol del mundo",
  "Path of the Zealot": "Senda del zelote",
  "College of Dance": "Colegio de danza",
  "College of Glamour": "Colegio de glamour",
  "College of Lore": "Colegio del saber",
  "College of Valor": "Colegio del valor",
  "Circle of the Land": "Circulo de la tierra",
  "Circle of the Moon": "Circulo de la luna",
  "Circle of the Sea": "Circulo del mar",
  "Circle of the Stars": "Circulo de las estrellas",
  "Warrior of Mercy": "Guerrero de la misericordia",
  "Warrior of Shadow": "Guerrero de las sombras",
  "Warrior of the Elements": "Guerrero de los elementos",
  "Warrior of the Open Hand": "Guerrero de la mano abierta",
  "Oath of Devotion": "Juramento de devocion",
  "Oath of Glory": "Juramento de gloria",
  "Oath of the Ancients": "Juramento de los antiguos",
  "Oath of Vengeance": "Juramento de venganza",
  "Beast Master": "Maestro de bestias",
  "Fey Wanderer": "Errante feerico",
  "Gloom Stalker": "Acechador sombrio",
  Hunter: "Cazador",
  "Arcane Trickster": "Tramposo arcano",
  Assassin: "Asesino",
  Soulknife: "Hoja psiquica",
  Thief: "Ladron",
  "Aberrant Sorcery": "Hechiceria aberrante",
  "Clockwork Sorcery": "Hechiceria mecanica",
  "Draconic Sorcery": "Hechiceria draconica",
  "Wild Magic Sorcery": "Hechiceria salvaje",
  "Archfey Patron": "Patrono archifeerico",
  "Celestial Patron": "Patrono celestial",
  "Fiend Patron": "Patrono infernal",
  "Great Old One Patron": "Patrono gran antiguo",
  Alchemist: "Alquimista",
  Armorer: "Armero",
  Artillerist: "Artillero",
  "Battle Smith": "Herrero de batalla",
  "life-domain": "Dominio de vida",
  "light-domain": "Dominio de luz",
  "trickery-domain": "Dominio del engano",
  "war-domain": "Dominio de guerra",
  berserker: "Senda del berserker",
  "wild-heart": "Senda del corazon salvaje",
  "world-tree": "Senda del arbol del mundo",
  zealot: "Senda del zelote",
  "dance-college": "Colegio de danza",
  "glamour-college": "Colegio de glamour",
  "lore-college": "Colegio del saber",
  "valor-college": "Colegio del valor",
  "land-circle": "Circulo de la tierra",
  "moon-circle": "Circulo de la luna",
  "sea-circle": "Circulo del mar",
  "stars-circle": "Circulo de las estrellas",
  "mercy-warrior": "Guerrero de la misericordia",
  "shadow-warrior": "Guerrero de las sombras",
  "elements-warrior": "Guerrero de los elementos",
  "open-hand-warrior": "Guerrero de la mano abierta",
  "devotion-oath": "Juramento de devocion",
  "glory-oath": "Juramento de gloria",
  "ancients-oath": "Juramento de los antiguos",
  "vengeance-oath": "Juramento de venganza",
  "beast-master": "Maestro de bestias",
  "fey-wanderer": "Errante feerico",
  "gloom-stalker": "Acechador sombrio",
  hunter: "Cazador",
  "arcane-trickster": "Tramposo arcano",
  assassin: "Asesino",
  soulknife: "Hoja psiquica",
  thief: "Ladron",
  "aberrant-sorcery": "Hechiceria aberrante",
  "clockwork-sorcery": "Hechiceria mecanica",
  "draconic-sorcery": "Hechiceria draconica",
  "wild-magic-sorcery": "Hechiceria salvaje",
  "archfey-patron": "Patrono archifeerico",
  "celestial-patron": "Patrono celestial",
  "fiend-patron": "Patrono infernal",
  "great-old-one-patron": "Patrono gran antiguo",
  "beast-land": "Bestia de tierra",
  "beast-sea": "Bestia de mar",
  "beast-sky": "Bestia de cielo",
  "colossus-slayer": "Azote de colosos",
  "horde-breaker": "Rompehordas",
  protector: "Protector",
  thaumaturge: "Taumaturgo",
  divineOrder: "Orden divina",
  magician: "Magico",
  warden: "Guardian",
  primalOrder: "Orden primal",
  spell: "Conjuro",
  cantrip: "Truco",
  spellbook: "Grimorio",
  arid: "Arida",
  polar: "Polar",
  temperate: "Templada",
  tropical: "Tropical",
  Human: "Humano",
  Elf: "Elfo",
  Aasimar: "Aasimar",
  Dragonborn: "Draconido",
  Dwarf: "Enano",
  Gnome: "Gnomo",
  Goliath: "Goliat",
  Halfling: "Mediano",
  Orc: "Orco",
  Tiefling: "Tiefling",
  Acolyte: "Acolito",
  Artisan: "Artesano",
  Charlatan: "Charlatan",
  Criminal: "Criminal",
  Entertainer: "Artista",
  Farmer: "Granjero",
  Guard: "Guardia",
  Guide: "Guia",
  Hermit: "Ermitano",
  Merchant: "Mercader",
  Noble: "Noble",
  Sage: "Sabio",
  Sailor: "Marinero",
  Scribe: "Escriba",
  Soldier: "Soldado",
  Wayfarer: "Errante",
  Small: "Pequeno",
  "Small or Medium": "Pequeno o Mediano",
  "Light": "Ligera",
  "Medium": "Media",
  "Heavy": "Pesada",
  "Shields": "Escudos",
  "Simple weapons": "Armas simples",
  "Martial weapons": "Armas marciales",
  "Martial light weapons": "Armas marciales ligeras",
  "Martial finesse or light weapons": "Armas marciales sutiles o ligeras",
  Acrobatics: "Acrobacias",
  "Animal Handling": "Trato con animales",
  Arcana: "Arcanos",
  Athletics: "Atletismo",
  Deception: "Engano",
  History: "Historia",
  Insight: "Perspicacia",
  Intimidation: "Intimidacion",
  Investigation: "Investigacion",
  Medicine: "Medicina",
  Nature: "Naturaleza",
  Perception: "Percepcion",
  Performance: "Interpretacion",
  Persuasion: "Persuasion",
  Religion: "Religion",
  "Sleight of Hand": "Juego de manos",
  Stealth: "Sigilo",
  Survival: "Supervivencia",
  Common: "Comun",
  "Thieves' Cant": "Jerga de ladrones",
  Druidic: "Druidico",
  Dwarvish: "Enano",
  Elvish: "Elfico",
  Giant: "Gigante",
  Gnomish: "Gnomo",
  Goblin: "Goblin",
  Halfling: "Mediano",
  Orc: "Orco",
  "magic-initiate-cleric": "Iniciado magico (Clerigo)",
  "magic-initiate-druid": "Iniciado magico (Druida)",
  "magic-initiate-wizard": "Iniciado magico (Mago)",
  alert: "Alerta",
  crafter: "Artesano",
  healer: "Sanador",
  lucky: "Afortunado",
  musician: "Musico",
  "savage-attacker": "Atacante salvaje",
  skilled: "Habilidoso",
  "tavern-brawler": "Peleador de taberna",
  tough: "Duro",
  "artificer-initiate": "Iniciado artificiero",
  chef: "Cocinero",
  crusher: "Triturador",
  "eldritch-adept": "Adepto sobrenatural",
  "fey-touched": "Tocado por las hadas",
  "fighting-initiate": "Iniciado en combate",
  gunner: "Pistolero",
  "metamagic-adept": "Adepto metamagico",
  piercer: "Perforador",
  poisoner: "Envenenador",
  "shadow-touched": "Tocado por las sombras",
  "skill-expert": "Experto en habilidades",
  slasher: "Cortador",
  telekinetic: "Telequinetico",
  telepathic: "Telepatico",
  "bountiful-luck": "Suerte generosa",
  "dragon-fear": "Miedo draconico",
  "dragon-hide": "Piel draconica",
  "drow-high-magic": "Alta magia drow",
  "dwarven-fortitude": "Fortaleza enana",
  "elven-accuracy": "Precision elfica",
  "fade-away": "Desvanecerse",
  "fey-teleportation": "Teleportacion feerica",
  "flames-of-phlegethos": "Llamas de Flegetos",
  "infernal-constitution": "Constitucion infernal",
  "orcish-fury": "Furia orca",
  prodigy: "Prodigio",
  "second-chance": "Segunda oportunidad",
  "squat-nimbleness": "Agilidad compacta",
  "wood-elf-magic": "Magia de elfo de bosque",
  club: "Garrote",
  dagger: "Daga",
  "daggers-2": "2 dagas",
  "daggers-5": "5 dagas",
  "psychic-blade": "Hoja psiquica",
  greatclub: "Gran garrote",
  handaxe: "Hacha de mano",
  javelin: "Jabalina",
  "javelins-6": "6 jabalinas",
  "light-hammer": "Martillo ligero",
  mace: "Maza",
  quarterstaff: "Baston",
  sickle: "Hoz",
  spear: "Lanza",
  dart: "Dardo",
  "light-crossbow": "Ballesta ligera",
  shortbow: "Arco corto",
  sling: "Honda",
  battleaxe: "Hacha de batalla",
  flail: "Mangual",
  glaive: "Guja",
  greataxe: "Gran hacha",
  greatsword: "Espadon",
  halberd: "Alabarda",
  lance: "Lanza de caballeria",
  longsword: "Espada larga",
  maul: "Gran maza",
  morningstar: "Lucero del alba",
  pike: "Pica",
  rapier: "Estoque",
  scimitar: "Cimitarra",
  shortsword: "Espada corta",
  trident: "Tridente",
  warhammer: "Martillo de guerra",
  "war-pick": "Pico de guerra",
  whip: "Latigo",
  blowgun: "Cerbatana",
  "hand-crossbow": "Ballesta de mano",
  "heavy-crossbow": "Ballesta pesada",
  longbow: "Arco largo",
  musket: "Mosquete",
  pistol: "Pistola",
  "smiths-tools": "Herramientas de herrero",
  "alchemists-supplies": "Suministros de alquimista",
  "brewers-supplies": "Suministros de cervecero",
  "cobblers-tools": "Herramientas de zapatero",
  "glassblowers-tools": "Herramientas de soplador de vidrio",
  "jewelers-tools": "Herramientas de joyero",
  "leatherworkers-tools": "Herramientas de peletero",
  "potters-tools": "Herramientas de alfarero",
  "tinkers-tools": "Herramientas de hojalatero",
  "weavers-tools": "Herramientas de tejedor",
  "woodcarvers-tools": "Herramientas de tallador",
  "painters-supplies": "Suministros de pintor",
  "masons-tools": "Herramientas de albanil",
  lute: "Laud",
  flute: "Flauta",
  drum: "Tambor",
  horn: "Cuerno",
  viol: "Viola",
  bagpipes: "Gaita",
  dulcimer: "Dulcimer",
  lyre: "Lira",
  "pan-flute": "Flauta de pan",
  shawm: "Chirimia",
  actor: "Actor",
  athlete: "Atleta",
  charger: "Cargador",
  "crossbow-expert": "Experto en ballestas",
  "defensive-duelist": "Duelista defensivo",
  "dual-wielder": "Combatiente dual",
  durable: "Duradero",
  "elemental-adept": "Adepto elemental",
  grappler: "Luchador",
  "great-weapon-master": "Maestro de armas grandes",
  "heavily-armored": "Armadura pesada",
  "heavy-armor-master": "Maestro de armadura pesada",
  "inspiring-leader": "Lider inspirador",
  "keen-mind": "Mente aguda",
  "lightly-armored": "Armadura ligera",
  "mage-slayer": "Azote de magos",
  "martial-weapon-training": "Entrenamiento con armas marciales",
  "medium-armor-master": "Maestro de armadura media",
  "moderately-armored": "Armadura media",
  "mounted-combatant": "Combatiente montado",
  observant: "Observador",
  "polearm-master": "Maestro de armas de asta",
  resilient: "Resiliente",
  "ritual-caster": "Lanzador ritual",
  sentinel: "Centinela",
  sharpshooter: "Tirador preciso",
  "shield-spell": "Escudo",
  "shield-master": "Maestro del escudo",
  skulker: "Acechador",
  speedy: "Veloz",
  "spell-sniper": "Francotirador de conjuros",
  "war-caster": "Conjurador de guerra",
  "weapon-master": "Maestro de armas",
  archery: "Tiro con arco",
  "blind-fighting": "Combate a ciegas",
  defense: "Defensa",
  dueling: "Duelo",
  "great-weapon-fighting": "Combate con arma grande",
  interception: "Intercepcion",
  protection: "Proteccion",
  "thrown-weapon-fighting": "Combate con armas arrojadizas",
  "two-weapon-fighting": "Combate con dos armas",
  "unarmed-fighting": "Combate sin armas",
  "blessed-warrior": "Guerrero bendito",
  "druidic-warrior": "Guerrero druidico",
  "careful-spell": "Conjuro cuidadoso",
  "distant-spell": "Conjuro distante",
  "empowered-spell": "Conjuro potenciado",
  "extended-spell": "Conjuro prolongado",
  "heightened-spell": "Conjuro intensificado",
  "quickened-spell": "Conjuro acelerado",
  "seeking-spell": "Conjuro buscador",
  "subtle-spell": "Conjuro sutil",
  "transmuted-spell": "Conjuro transmutado",
  "twinned-spell": "Conjuro duplicado",
  artificer: "Artifice",
  alchemist: "Alquimista",
  armorer: "Armero",
  artillerist: "Artillero",
  "battle-smith": "Herrero de batalla",
  "armor-flail": "Mangual de armadura",
  "thunder-gauntlets": "Guanteletes atronadores",
  "lightning-launcher": "Lanzador relampago",
  dreadnaught: "Acorazado",
  guardian: "Guardian",
  infiltrator: "Infiltrador",
  "alchemy-jug": "Jarra alquimica",
  "bag-of-holding": "Bolsa de contencion",
  "cap-of-water-breathing": "Gorro de respirar bajo el agua",
  "common-magic-item": "Objeto magico comun permitido",
  "goggles-of-night": "Gafas de vision nocturna",
  "rope-of-climbing": "Cuerda de trepar",
  "sending-stones": "Piedras mensajeras",
  "shield-plus-one": "Escudo +1",
  "wand-of-magic-detection": "Varita de deteccion magica",
  "wand-of-secrets": "Varita de secretos",
  "wand-of-the-war-mage-plus-one": "Varita del mago de guerra +1",
  "weapon-plus-one": "Arma +1",
  "agonizing-blast": "Explosion agonizante",
  "armor-of-shadows": "Armadura de sombras",
  "ascendant-step": "Paso ascendente",
  "devils-sight": "Vista del diablo",
  "eldritch-mind": "Mente sobrenatural",
  "eldritch-smite": "Castigo sobrenatural",
  "eldritch-spear": "Lanza sobrenatural",
  "fiendish-vigor": "Vigor infernal",
  "gaze-of-two-minds": "Mirada de dos mentes",
  "gift-of-the-depths": "Don de las profundidades",
  "investment-of-the-chain-master": "Inversion del amo de la cadena",
  "lessons-of-the-first-ones": "Lecciones de los primeros",
  "mask-of-many-faces": "Mascara de muchos rostros",
  "master-of-myriad-forms": "Maestro de mil formas",
  "misty-visions": "Visiones brumosas",
  "one-with-shadows": "Uno con las sombras",
  "otherworldly-leap": "Salto de otro mundo",
  "pact-of-the-blade": "Pacto de la hoja",
  "pact-of-the-chain": "Pacto de la cadena",
  "pact-of-the-tome": "Pacto del tomo",
  "repelling-blast": "Explosion repelente",
  "thirsting-blade": "Hoja sedienta",
  Acid: "Acido",
  Cold: "Frio",
  Lightning: "Relampago",
  Thunder: "Trueno",
  Bludgeoning: "Contundente",
  Piercing: "Perforante",
  Slashing: "Cortante",
  Cleave: "Hendedora",
  Graze: "Rozar",
  Nick: "Mellar",
  Push: "Empujar",
  Sap: "Debilitar",
  Slow: "Ralentizar",
  Topple: "Derribar",
  Vex: "Hostigar",
  armor: "Armadura",
  shield: "Escudo",
  weapon: "Arma",
  gear: "Equipo",
  tool: "Herramienta",
  focus: "Foco",
  pack: "Paquete",
  "calligraphers-supplies": "Suministros de caligrafo",
  "carpenters-tools": "Herramientas de carpintero",
  "cartographers-tools": "Herramientas de cartografo",
  "forgery-kit": "Kit de falsificacion",
  "herbalism-kit": "Kit de herboristeria",
  "navigators-tools": "Herramientas de navegante",
  "disguise-kit": "Kit de disfraz",
  "poisoners-kit": "Kit de envenenador",
  "thieves-tools": "Herramientas de ladron",
  "gaming-set": "Juego",
  "musical-instrument": "Instrumento musical",
  "artisan-tools": "Herramientas de artesano",
  "chosen-tool": "Herramienta o instrumento elegido",
  "burglars-pack": "Paquete de ladron",
  Black: "Negro - acido",
  Blue: "Azul - relampago",
  Brass: "Laton - fuego",
  Bronze: "Bronce - relampago",
  Copper: "Cobre - acido",
  Gold: "Oro - fuego",
  Green: "Verde - veneno",
  Red: "Rojo - fuego",
  Silver: "Plata - frio",
  White: "Blanco - frio",
  Drow: "Drow",
  "High Elf": "Alto elfo",
  "Wood Elf": "Elfo de bosque",
  "Forest Gnome": "Gnomo del bosque",
  "Rock Gnome": "Gnomo de roca",
  Cloud: "Nube",
  Fire: "Fuego",
  Frost: "Escarcha",
  Hill: "Colina",
  Stone: "Piedra",
  Storm: "Tormenta",
  Abyssal: "Abisal",
  Chthonic: "Ctonico",
  Infernal: "Infernal",
  "burning-hands": "Manos ardientes",
  "blade-of-disaster": "Hoja del desastre",
  "booming-blade": "Hoja retumbante",
  "charm-person": "Hechizar persona",
  command: "Orden imperiosa",
  "cure-wounds": "Curar heridas",
  "detect-magic": "Detectar magia",
  "disguise-self": "Disfrazarse",
  "dream-of-the-blue-veil": "Sueno del velo azul",
  "faerie-fire": "Fuego feerico",
  "false-life": "Vida falsa",
  "fire-bolt": "Descarga de fuego",
  "gift-of-alacrity": "Don de presteza",
  "green-flame-blade": "Hoja de llama verde",
  guidance: "Guia",
  hex: "Maleficio",
  jump: "Saltar",
  light: "Luz",
  "lightning-lure": "Atraccion relampago",
  "mage-armor": "Armadura de mago",
  "mage-hand": "Mano de mago",
  "magic-missile": "Proyectil magico",
  mending: "Remendar",
  "mind-sliver": "Astilla mental",
  "minor-illusion": "Ilusion menor",
  prestidigitation: "Prestidigitacion",
  "ray-of-frost": "Rayo de escarcha",
  sanctuary: "Santuario",
  shield: "Escudo",
  "shocking-grasp": "Agarre electrizante",
  "sorcerous-burst": "Estallido hechicero",
  "eldritch-blast": "Explosion sobrenatural",
  "armor-of-agathys": "Armadura de Agathys",
  "hellish-rebuke": "Represalia infernal",
  hex: "Maleficio",
  enthrall: "Fascinar",
  "ray-of-enfeeblement": "Rayo debilitador",
  "remove-curse": "Quitar maldicion",
  "silent-image": "Imagen silenciosa",
  "arms-of-hadar": "Brazos de Hadar",
  "hunger-of-hadar": "Hambre de Hadar",
  "rarys-telepathic-bond": "Vinculo telepatico de Rary",
  "evards-black-tentacles": "Tentaculos negros de Evard",
  "summon-dragon": "Convocar dragon",
  "spirit-shroud": "Sudario espiritual",
  "summon-aberration": "Convocar aberracion",
  "summon-beast": "Convocar bestia",
  "summon-celestial": "Convocar celestial",
  "summon-construct": "Convocar constructo",
  "summon-elemental": "Convocar elemental",
  "summon-fey": "Convocar hada",
  "summon-fiend": "Convocar infernal",
  "summon-shadowspawn": "Convocar engendro sombrio",
  "summon-undead": "Convocar muerto viviente",
  "sword-burst": "Estallido de espadas",
  "tashas-caustic-brew": "Brebaje caustico de Tasha",
  "tashas-mind-whip": "Latigo mental de Tasha",
  "tashas-otherworldly-guise": "Apariencia sobrenatural de Tasha",
  thunderwave: "Onda atronadora",
  "Fire Bolt": "Descarga de fuego",
  "Mage Hand": "Mano de mago",
  Shield: "Escudo",
};

export function displayName(item) {
  if (!item) {
    return "";
  }

  if (typeof item === "string") {
    return displayValue(item);
  }

  return item.label || item.name || item.id || "";
}

export function displayValue(value) {
  return valueLabels[value] || getSpellSheetDetail(value)?.label || value;
}

export function displayList(values) {
  if (!Array.isArray(values)) {
    return values;
  }

  return values.map(displayValue);
}

export function displayChoiceOption(choice, option) {
  return choice.optionLabels?.[option] || displayValue(option);
}
