export const spellSheetDetails = {
  "acid-splash": { label: "Salpicadura acida", detail: "salvacion DES; 2d6 acido a nivel 5; esfera 5 pies." },
  "blade-ward": { label: "Custodia de cuchillas", detail: "concentracion; defensa contra ataques con arma." },
  "chill-touch": { label: "Toque helado", detail: "ataque de conjuro; 2d10 necrotico a nivel 5; impide curacion." },
  "dancing-lights": { label: "Luces danzantes", detail: "concentracion; crea luces pequenas." },
  elementalism: { label: "Elementalismo", detail: "efectos elementales menores." },
  "fire-bolt": { label: "Descarga de fuego", detail: "ataque de conjuro; 2d10 fuego a nivel 5" },
  friends: { label: "Amistad", detail: "concentracion; ventaja social breve." },
  light: { label: "Luz", detail: "objeto ilumina 20/20 pies." },
  "mage-hand": { label: "Mano de mago", detail: "mano espectral; manipula objetos a distancia." },
  mending: { label: "Remendar", detail: "repara una rotura o rasgadura menor." },
  message: { label: "Mensaje", detail: "susurro magico a distancia." },
  "mind-sliver": { label: "Astilla mental", detail: "salvacion INT; 2d6 psiquico a nivel 5; resta 1d4 a la proxima salvacion." },
  "minor-illusion": { label: "Ilusion menor", detail: "crea sonido o imagen ilusoria." },
  "poison-spray": { label: "Rociada venenosa", detail: "salvacion CON; 2d12 veneno a nivel 5." },
  prestidigitation: { label: "Prestidigitacion", detail: "efectos magicos menores." },
  "ray-of-frost": { label: "Rayo de escarcha", detail: "ataque de conjuro; 2d8 frio a nivel 5; reduce velocidad 10 pies." },
  "shocking-grasp": { label: "Agarre electrizante", detail: "ataque de conjuro; 2d8 relampago a nivel 5; sin reacciones." },
  "sorcerous-burst": { label: "Estallido hechicero", detail: "ataque de conjuro; 2d8 tipo elegido a nivel 5; los 8 pueden explotar." },
  thunderclap: { label: "Trueno", detail: "salvacion CON; 2d6 trueno a nivel 5; area 5 pies." },
  "toll-the-dead": { label: "Doblar de muertos", detail: "salvacion SAB; 2d8 necrotico, o 2d12 si el objetivo esta herido." },
  "true-strike": { label: "Golpe certero", detail: "ataque con arma usando aptitud magica; dano radiante extra a niveles altos." },
  guidance: { label: "Guia", detail: "concentracion; suma 1d4 a una prueba de caracteristica." },
  resistance: { label: "Resistencia", detail: "concentracion; suma 1d4 a una salvacion." },
  "sacred-flame": { label: "Llama sagrada", detail: "salvacion DES; 2d8 radiante a nivel 5; ignora cobertura." },
  "spare-the-dying": { label: "Perdonar a los moribundos", detail: "estabiliza una criatura moribunda." },
  thaumaturgy: { label: "Taumaturgia", detail: "manifestacion divina menor." },
  "word-of-radiance": { label: "Palabra de radiancia", detail: "salvacion CON; 2d6 radiante a nivel 5 alrededor de ti." },
  druidcraft: { label: "Druidismo", detail: "efecto natural menor; predice clima, hace brotar o altera sensaciones naturales." },
  "produce-flame": { label: "Producir llama", detail: "crea llama en la mano; ataque de conjuro, 2d8 fuego a nivel 5." },
  shillelagh: { label: "Shillelagh", detail: "baston/garrote usa Sabiduria para ataque y dano; dano 1d8." },
  "thorn-whip": { label: "Latigo de espinas", detail: "ataque de conjuro; 2d6 perforante a nivel 5; atrae 10 pies si es Grande o menor." },

  bane: { label: "Perdicion", detail: "concentracion; resta 1d4 a ataques y salvaciones." },
  bless: { label: "Bendecir", detail: "concentracion; suma 1d4 a ataques y salvaciones.", higherLevel: "+1 objetivo por cada nivel de espacio sobre 1." },
  command: { label: "Orden imperiosa", detail: "salvacion SAB; una orden breve." },
  "compelled-duel": { label: "Duelo obligado", detail: "concentracion; salvacion SAB; fuerza a un enemigo a centrarse en ti." },
  "create-or-destroy-water": { label: "Crear o destruir agua", detail: "crea o destruye agua; utilitario." },
  "cure-wounds": { label: "Curar heridas", detail: "toque; cura 2d8 + aptitud magica.", higherLevel: "+2d8 de curacion por cada nivel de espacio sobre 1." },
  "detect-evil-and-good": { label: "Detectar el mal y el bien", detail: "concentracion; detecta criaturas/zonas sobrenaturales." },
  "detect-poison-and-disease": { label: "Detectar veneno y enfermedad", detail: "concentracion, ritual; detecta venenos, enfermedades y criaturas infectadas." },
  "guiding-bolt": { label: "Rayo guiador", detail: "ataque de conjuro; 4d6 radiante; ventaja al proximo ataque contra el objetivo." },
  "divine-favor": { label: "Favor divino", detail: "accion adicional; tus ataques con arma hacen +1d4 radiante." },
  "divine-smite": { label: "Castigo divino", detail: "accion adicional tras impactar; +2d8 radiante, +1d8 contra infernal o no muerto." },
  "healing-word": { label: "Palabra sanadora", detail: "accion adicional; cura 2d4 + aptitud magica a 60 pies.", higherLevel: "+2d4 de curacion por cada nivel de espacio sobre 1." },
  "inflict-wounds": { label: "Infligir heridas", detail: "salvacion CON; 2d10 necrotico." },
  "protection-from-evil-and-good": { label: "Proteccion contra el mal y el bien", detail: "concentracion; protege contra aberraciones, celestiales, feericos, infernales, elementales y no muertos." },
  "purify-food-and-drink": { label: "Purificar comida y bebida", detail: "ritual; purifica alimento y bebida." },
  sanctuary: { label: "Santuario", detail: "salvacion SAB para atacar al protegido." },
  "shield-of-faith": { label: "Escudo de fe", detail: "concentracion; +2 CA." },
  "searing-smite": { label: "Castigo abrasador", detail: "accion adicional tras impactar; dano fuego y puede seguir ardiendo." },
  "thunderous-smite": { label: "Castigo atronador", detail: "accion adicional tras impactar; dano trueno y empuja/derriba." },
  "wrathful-smite": { label: "Castigo colerico", detail: "accion adicional tras impactar; dano necrotico y puede Asustar." },
  "burning-hands": { label: "Manos ardientes", detail: "salvacion DES; 3d6 fuego; cono 15 pies.", higherLevel: "+1d6 fuego por cada nivel de espacio sobre 1." },
  "charm-person": { label: "Hechizar persona", detail: "salvacion SAB; humanoide queda hechizado." },
  "chromatic-orb": { label: "Orbe cromatico", detail: "ataque de conjuro; 3d8 acido/frio/fuego/relampago/trueno/veneno." },
  "color-spray": { label: "Rociada de color", detail: "cono 15 pies.; ciega criaturas afectadas." },
  "detect-magic": { label: "Detectar magia", detail: "concentracion, ritual; detecta magia 30 pies." },
  "disguise-self": { label: "Disfrazarse", detail: "cambia tu apariencia 1 hora." },
  "false-life": { label: "Vida falsa", detail: "gana 2d4 + 4 PG temporales.", higherLevel: "+5 PG temporales por cada nivel de espacio sobre 1." },
  "feather-fall": { label: "Caida de pluma", detail: "reaccion; hasta 5 criaturas caen lento." },
  "find-familiar": { label: "Encontrar familiar", detail: "ritual; invoca familiar." },
  "fog-cloud": { label: "Nube de niebla", detail: "concentracion; area oscurecida." },
  grease: { label: "Grasa", detail: "salvacion DES; area dificil y caidas." },
  entangle: { label: "Enredar", detail: "concentracion; terreno dificil, salvacion FUE o queda Restrenido." },
  goodberry: { label: "Bayas buenas", detail: "crea 10 bayas; cada una cura 1 PG y alimenta por un dia." },
  "ice-knife": { label: "Cuchillo de hielo", detail: "ataque de conjuro 1d10 perforante; explota 2d6 frio, salvacion DES." },
  identify: { label: "Identificar", detail: "ritual; identifica propiedades magicas." },
  jump: { label: "Saltar", detail: "aumenta distancia de salto." },
  "mage-armor": { label: "Armadura de mago", detail: "CA base 13 + DES; dura 8 h." },
  "magic-missile": { label: "Proyectil magico", detail: "3 dardos; cada uno 1d4 + 1 fuerza; impacta automatico.", higherLevel: "+1 dardo por cada nivel de espacio sobre 1." },
  "ray-of-sickness": { label: "Rayo nauseabundo", detail: "ataque de conjuro; 2d8 veneno y salvacion CON contra envenenado." },
  shield: { label: "Escudo", detail: "reaccion; +5 CA hasta tu proximo turno; bloquea Proyectil magico" },
  "shield-spell": { label: "Escudo", detail: "reaccion; +5 CA hasta tu proximo turno; bloquea Proyectil magico" },
  "silent-image": { label: "Imagen silenciosa", detail: "concentracion; ilusion visual." },
  sleep: { label: "Dormir", detail: "concentracion; afecta criaturas segun PG." },
  "tashas-hideous-laughter": { label: "Risa horrible de Tasha", detail: "salvacion SAB; objetivo cae incapacitado y tumbado." },
  "thunderwave": { label: "Onda atronadora", detail: "salvacion CON; 2d8 trueno y empuja 10 pies.; cubo 15 pies.", higherLevel: "+1d8 trueno por cada nivel de espacio sobre 1." },
  "witch-bolt": { label: "Rayo de bruja", detail: "ataque de conjuro; 2d12 relampago, concentracion." },

  "arcane-vigor": { label: "Vigor arcano", detail: "recupera PG usando dados disponibles del conjuro." },
  aid: { label: "Ayuda", detail: "aumenta PG maximos y actuales de aliados.", higherLevel: "+5 PG por cada nivel de espacio sobre 2." },
  augury: { label: "Augurio", detail: "ritual; presagio sobre un curso de accion." },
  "arcane-lock": { label: "Cerradura arcana", detail: "bloquea magicamente una puerta, cofre o entrada." },
  barkskin: { label: "Piel robliza", detail: "CA minima 17 del objetivo mientras dure." },
  "beast-sense": { label: "Sentidos de bestia", detail: "concentracion, ritual; percibes mediante una bestia voluntaria." },
  "blindness-deafness": { label: "Ceguera/Sordera", detail: "salvacion CON; ciega o ensordece." },
  "calm-emotions": { label: "Calmar emociones", detail: "concentracion; suprime encanto/miedo u hostilidad." },
  blur: { label: "Desenfocar", detail: "concentracion; ataques contra ti tienen desventaja." },
  "cloud-of-daggers": { label: "Nube de dagas", detail: "concentracion; 4d4 cortante en cubo 5 pies.", higherLevel: "+2d4 cortante por cada nivel de espacio sobre 2." },
  "continual-flame": { label: "Llama continua", detail: "crea una llama magica que ilumina y no consume combustible." },
  darkness: { label: "Oscuridad", detail: "concentracion; oscuridad magica." },
  darkvision: { label: "Vision en la oscuridad", detail: "otorga vision en la oscuridad 60 pies." },
  "detect-thoughts": { label: "Detectar pensamientos", detail: "concentracion; lee pensamientos superficiales." },
  "dragons-breath": { label: "Aliento de dragon", detail: "concentracion; accion para cono 15 pies.; 3d6 tipo elegido.", higherLevel: "+1d6 por cada nivel de espacio sobre 2." },
  "enhance-ability": { label: "Mejorar caracteristica", detail: "concentracion; ventaja en pruebas de un atributo y beneficio menor." },
  "enlarge-reduce": { label: "Agrandar/Reducir", detail: "concentracion; cambia tamano, dano y pruebas de Fuerza." },
  "find-traps": { label: "Encontrar trampas", detail: "detecta trampas dentro del alcance." },
  "flame-blade": { label: "Hoja flamigera", detail: "concentracion; ataque de conjuro cuerpo a cuerpo, 3d6 fuego." },
  "flaming-sphere": { label: "Esfera flamigera", detail: "concentracion; 2d6 fuego, salvacion DES." },
  "gentle-repose": { label: "Dulce descanso", detail: "ritual; preserva un cadaver." },
  "hold-person": { label: "Inmovilizar persona", detail: "salvacion SAB; paraliza humanoide.", higherLevel: "+1 objetivo por cada nivel de espacio sobre 2." },
  "homunculus-servant": { label: "Servidor homunculo", detail: "ritual; crea servidor constructo con gema o cristal de 100+ PO." },
  "lesser-restoration": { label: "Restauracion menor", detail: "termina una enfermedad o condicion especifica." },
  invisibility: { label: "Invisibilidad", detail: "concentracion; objetivo invisible." },
  levitate: { label: "Levitar", detail: "concentracion; criatura u objeto sube o baja verticalmente." },
  "locate-object": { label: "Localizar objeto", detail: "concentracion; detecta direccion de un objeto." },
  "magic-weapon": { label: "Arma magica", detail: "vuelve magica un arma y mejora ataque/dano." },
  "melfs-acid-arrow": { label: "Flecha acida de Melf", detail: "ataque de conjuro; 4d4 acido y 2d4 acido posterior." },
  "mirror-image": { label: "Imagen multiple", detail: "crea duplicados defensivos; no requiere concentracion." },
  "misty-step": { label: "Paso brumoso", detail: "accion adicional; teletransporte 30 pies" },
  moonbeam: { label: "Rayo lunar", detail: "concentracion; salvacion CON, 2d10 radiante en cilindro 5 pies." },
  "protection-from-poison": { label: "Proteccion contra veneno", detail: "neutraliza veneno o da resistencia y ventaja contra veneno." },
  "find-steed": { label: "Encontrar montura", detail: "invoca montura sobrenatural aliada; dura hasta desaparecer o morir." },
  "scorching-ray": { label: "Rayo abrasador", detail: "3 ataques de conjuro; cada rayo 2d6 fuego.", higherLevel: "+1 rayo por cada nivel de espacio sobre 2." },
  shatter: { label: "Estallar", detail: "salvacion CON; 3d8 trueno; esfera 10 pies.", higherLevel: "+1d8 trueno por cada nivel de espacio sobre 2." },
  silence: { label: "Silencio", detail: "concentracion, ritual; zona sin sonido." },
  "spike-growth": { label: "Crecimiento de espinas", detail: "concentracion; terreno dificil oculto, 2d4 perforante por cada 5 pies movidos." },
  "spider-climb": { label: "Trepar cual arana", detail: "concentracion; trepa paredes y techos con manos libres." },
  "spiritual-weapon": { label: "Arma espiritual", detail: "concentracion; ataque de conjuro con arma flotante." },
  "shining-smite": { label: "Castigo brillante", detail: "concentracion; accion adicional tras impactar; el objetivo brilla y recibe dano radiante." },
  suggestion: { label: "Sugestion", detail: "salvacion SAB; orden razonable, concentracion." },
  "summon-beast": { label: "Convocar bestia", detail: "concentracion; invoca espiritu bestial que lucha contigo." },
  "warding-bond": { label: "Vinculo protector", detail: "+1 CA/salvaciones y resistencia; compartes dano." },
  web: { label: "Telarana", detail: "concentracion; terreno dificil y restriccion, salvacion DES." },
  "zone-of-truth": { label: "Zona de verdad", detail: "salvacion CAR; impide mentir dentro del area." },
  "arms-of-hadar": { label: "Brazos de Hadar", detail: "salvacion FUE; 2d6 necrotico y sin reacciones." },
  alarm: { label: "Alarma", detail: "ritual; protege zona y avisa si entra una criatura." },
  "armor-of-agathys": { label: "Armadura de Agathys", detail: "5 PG temporales por nivel de espacio; quien te golpea cuerpo a cuerpo recibe frio." },
  "hellish-rebuke": { label: "Represalia infernal", detail: "reaccion; salvacion DES; 2d10 fuego.", higherLevel: "+1d10 fuego por cada nivel de espacio sobre 1." },
  hex: { label: "Maleficio", detail: "concentracion; +1d6 necrotico al golpear al objetivo y penaliza una habilidad." },
  enthrall: { label: "Fascinar", detail: "concentracion; criaturas tienen desventaja para percibir a otros." },
  "ray-of-enfeeblement": { label: "Rayo debilitador", detail: "ataque de conjuro; objetivo hace la mitad de dano con ataques de Fuerza, concentracion." },
  "hunger-of-hadar": { label: "Hambre de Hadar", detail: "concentracion; oscuridad y dano frio/acido en area." },

  "animate-dead": { label: "Animar muertos", detail: "crea o mantiene un servidor no muerto." },
  "aura-of-vitality": { label: "Aura de vitalidad", detail: "concentracion; accion adicional para curar dentro del aura." },
  "beacon-of-hope": { label: "Faro de esperanza", detail: "concentracion; ventaja contra miedo/muerte y curacion maxima." },
  "bestow-curse": { label: "Lanzar maldicion", detail: "concentracion; impone maldicion a un objetivo." },
  clairvoyance: { label: "Clarividencia", detail: "concentracion; sensor invisible a distancia." },
  "call-lightning": { label: "Llamar relampagos", detail: "concentracion; salvacion DES, 3d10 relampago desde nube de tormenta." },
  "conjure-animals": { label: "Conjurar animales", detail: "concentracion; convoca espiritus bestiales para combatir." },
  "create-food-and-water": { label: "Crear comida y agua", detail: "crea alimento y agua para el grupo." },
  counterspell: { label: "Contrahechizo", detail: "reaccion; intenta interrumpir un conjuro." },
  daylight: { label: "Luz del dia", detail: "luz brillante amplia; puede disipar oscuridad magica." },
  "dispel-magic": { label: "Disipar magia", detail: "termina efectos magicos de nivel 3 o inferior; prueba si superior." },
  "elemental-weapon": { label: "Arma elemental", detail: "concentracion; arma magica con +1 al ataque y 1d4 dano elemental." },
  "feign-death": { label: "Simular muerte", detail: "ritual; objetivo parece muerto y queda protegido." },
  fireball: { label: "Bola de fuego", detail: "salvacion DES; 8d6 fuego; esfera 20 pies." },
  fly: { label: "Volar", detail: "concentracion; velocidad vuelo 60 pies." },
  haste: { label: "Prisa", detail: "concentracion; +2 CA, ventaja DES, accion extra limitada." },
  "hypnotic-pattern": { label: "Patron hipnotico", detail: "salvacion SAB; incapacita en cubo 30 pies., concentracion." },
  "magic-circle": { label: "Circulo magico", detail: "protege o encierra criaturas sobrenaturales." },
  "mass-healing-word": { label: "Palabra sanadora en masa", detail: "accion adicional; cura varias criaturas." },
  "gaseous-form": { label: "Forma gaseosa", detail: "concentracion; objetivo se vuelve nube, vuela lento y resiste dano." },
  blink: { label: "Intermitencia", detail: "puedes desaparecer al Plano Etereo al final de tus turnos." },
  "eldritch-blast": { label: "Explosion sobrenatural", detail: "ataque de conjuro; 2 rayos a nivel 5, cada uno 1d10 fuerza." },
  "meld-into-stone": { label: "Fundirse con la piedra", detail: "ritual; entras en piedra." },
  nondetection: { label: "Indetectable", detail: "oculta contra adivinacion." },
  "pass-without-trace": { label: "Pasar sin dejar rastro", detail: "concentracion; +10 Sigilo al grupo." },
  "protection-from-energy": { label: "Proteccion contra energia", detail: "concentracion; resistencia a un tipo elemental." },
  "remove-curse": { label: "Quitar maldicion", detail: "termina maldicion sobre criatura u objeto." },
  revivify: { label: "Revivir", detail: "revive criatura muerta recientemente." },
  sending: { label: "Recado", detail: "mensaje breve a cualquier distancia." },
  "sleet-storm": { label: "Tormenta de aguanieve", detail: "concentracion; area helada y muy obstruida, afecta concentracion y caidas." },
  "lightning-bolt": { label: "Relampago", detail: "salvacion DES; 8d6 relampago; linea 100 pies." },
  slow: { label: "Ralentizar", detail: "salvacion SAB; reduce acciones, CA y velocidad, concentracion." },
  "speak-with-dead": { label: "Hablar con los muertos", detail: "preguntas a un cadaver." },
  "spirit-guardians": { label: "Guardianes espirituales", detail: "concentracion; area alrededor de ti, dano radiante/necrotico y ralentiza." },
  "stinking-cloud": { label: "Nube apestosa", detail: "salvacion CON; pierde accion dentro del area, concentracion." },
  "summon-fey": { label: "Convocar hada", detail: "concentracion; invoca espiritu feerico." },
  "summon-undead": { label: "Convocar muerto viviente", detail: "concentracion; invoca espiritu no muerto." },
  tongues: { label: "Lenguas", detail: "entiende y habla cualquier idioma." },
  "vampiric-touch": { label: "Toque vampirico", detail: "ataque de conjuro; 3d6 necrotico y te curas la mitad." },
  "water-breathing": { label: "Respirar bajo el agua", detail: "ritual; hasta 10 criaturas respiran bajo el agua." },
  "water-walk": { label: "Caminar sobre el agua", detail: "ritual; camina sobre liquidos." },
  "wind-wall": { label: "Muro de viento", detail: "concentracion; muro que bloquea proyectiles y causa 3d8 contundente." },
  "starry-wisp": { label: "Brizna estelar", detail: "ataque de conjuro; 2d8 radiante a nivel 5; el objetivo brilla." },
  "vicious-mockery": { label: "Burla cruel", detail: "salvacion SAB; 2d6 psiquico a nivel 5; desventaja al proximo ataque." },
  "animal-friendship": { label: "Amistad animal", detail: "salvacion SAB; bestia queda encantada." },
  "ensnaring-strike": { label: "Golpe atrapador", detail: "concentracion; ataque con arma enreda, salvacion FUE o Restrenido." },
  "hail-of-thorns": { label: "Lluvia de espinas", detail: "accion adicional tras impactar con arma a distancia; salvacion DES, dano perforante en area." },
  "comprehend-languages": { label: "Comprender idiomas", detail: "ritual; entiendes idiomas por 1 hora." },
  "dissonant-whispers": { label: "Susurros disonantes", detail: "salvacion SAB; 3d6 psiquico y el objetivo usa reaccion para alejarse." },
  "faerie-fire": { label: "Fuego feerico", detail: "concentracion; revela objetivos y da ventaja a ataques contra ellos." },
  heroism: { label: "Heroismo", detail: "concentracion; inmune a Asustado y gana PG temporales cada turno." },
  longstrider: { label: "Zancada prodigiosa", detail: "aumenta velocidad 10 pies." },
  "speak-with-animals": { label: "Hablar con animales", detail: "ritual; comunicate con bestias." },
  "unseen-servant": { label: "Sirviente invisible", detail: "ritual; servidor invisible para tareas simples." },
  "animal-messenger": { label: "Mensajero animal", detail: "ritual; envia un mensaje mediante una bestia pequena." },
  enthrall: { label: "Fascinar", detail: "concentracion; distrae criaturas con tu actuacion." },
  "heat-metal": { label: "Calentar metal", detail: "concentracion; 2d8 fuego a metal y posible desventaja." },
  "hunters-mark": { label: "Marca del cazador", detail: "concentracion; accion adicional; +1d6 dano al objetivo marcado." },
  "cordon-of-arrows": { label: "Cordon de flechas", detail: "preparas municion magica; criaturas cercanas activan salvacion DES o reciben dano." },
  "gust-of-wind": { label: "Rafaga de viento", detail: "concentracion; linea de viento que empuja, dificulta movimiento y dispersa gases." },
  knock: { label: "Abrir", detail: "abre o desatasca una cerradura, puerta o contenedor." },
  "locate-animals-or-plants": { label: "Localizar animales o plantas", detail: "ritual; encuentra especie animal o vegetal cercana." },
  "magic-mouth": { label: "Boca magica", detail: "ritual; mensaje magico activado por condicion." },
  "phantasmal-force": { label: "Fuerza fantasmal", detail: "concentracion; ilusion mental que puede danar." },
  "rope-trick": { label: "Truco de cuerda", detail: "crea espacio extradimensional oculto al final de una cuerda." },
  "see-invisibility": { label: "Ver invisibilidad", detail: "ves criaturas/objetos invisibles." },
  fear: { label: "Miedo", detail: "concentracion; cono 30 pies, salvacion SAB o Asustado." },
  "glyph-of-warding": { label: "Glifo custodio", detail: "glifo magico con efecto explosivo o conjuro almacenado." },
  "leomunds-tiny-hut": { label: "Cabana diminuta de Leomund", detail: "ritual; refugio inmovil por 8 horas." },
  "major-image": { label: "Imagen mayor", detail: "concentracion; ilusion visual, sonora y sensorial." },
  "plant-growth": { label: "Crecimiento vegetal", detail: "altera plantas; terreno muy dificil o mejora cosecha." },
  "speak-with-plants": { label: "Hablar con plantas", detail: "comunicate con plantas y manipula vegetacion cercana." },
};

export function getSpellSheetDetail(spellId) {
  return spellSheetDetails[spellId] || null;
}

