export const spellSheetDetails = {
  "acid-splash": { label: "Salpicadura acida", detail: "salvación DES; 2d6 Ácido a nivel 5; esfera 5 pies." },
  "blade-ward": { label: "Custodia de cuchillas", detail: "concentración; defensa contra ataques con arma." },
  "chill-touch": { label: "Toque helado", detail: "ataque de conjuro; 2d10 necrótico a nivel 5; impide curación." },
  "dancing-lights": { label: "Luces danzantes", detail: "concentración; crea luces pequeñas." },
  elementalism: { label: "Elementalismo", detail: "efectos elementales menores." },
  "fire-bolt": { label: "Descarga de fuego", detail: "ataque de conjuro; 2d10 fuego a nivel 5" },
  friends: { label: "Amistad", detail: "concentración; ventaja social breve." },
  light: { label: "Luz", detail: "objeto ilumina 20/20 pies." },
  "mage-hand": { label: "Mano de mago", detail: "mano espectral; manipula objetos a distancia." },
  mending: { label: "Remendar", detail: "repara una rotura o rasgadura menor." },
  message: { label: "Mensaje", detail: "susurro mágico a distancia." },
  "mind-sliver": { label: "Astilla mental", detail: "salvación INT; 2d6 psíquico a nivel 5; resta 1d4 a la próxima salvación." },
  "minor-illusion": { label: "Ilusión menor", detail: "crea sonido o imagen ilusoria." },
  "poison-spray": { label: "Rociada venenosa", detail: "salvación CON; 2d12 veneno a nivel 5." },
  prestidigitation: { label: "Prestidigitación", detail: "efectos mágicos menores." },
  "ray-of-frost": { label: "Rayo de escarcha", detail: "ataque de conjuro; 2d8 frío a nivel 5; reduce velocidad 10 pies." },
  "shocking-grasp": { label: "Agarre electrizante", detail: "ataque de conjuro; 2d8 relámpago a nivel 5; sin reacciones." },
  "sorcerous-burst": { label: "Estallido hechicero", detail: "ataque de conjuro; 2d8 tipo elegido a nivel 5; los 8 pueden explotar." },
  thunderclap: { label: "Trueno", detail: "salvación CON; 2d6 trueno a nivel 5; área 5 pies." },
  "toll-the-dead": { label: "Doblar de muertos", detail: "salvación SAB; 2d8 necrótico, o 2d12 si el objetivo está herido." },
  "true-strike": { label: "Golpe certero", detail: "ataque con arma usando aptitud mágica; daño radiante extra a niveles altos." },
  guidance: { label: "Guía", detail: "concentración; suma 1d4 a una prueba de característica." },
  resistance: { label: "Resistencia", detail: "concentración; suma 1d4 a una salvación." },
  "sacred-flame": { label: "Llama sagrada", detail: "salvación DES; 2d8 radiante a nivel 5; ignora cobertura." },
  "spare-the-dying": { label: "Perdonar a los moribundos", detail: "estabiliza una criatura moribunda." },
  thaumaturgy: { label: "Taumaturgia", detail: "manifestacion divina menor." },
  "word-of-radiance": { label: "Palabra de radiancia", detail: "salvación CON; 2d6 radiante a nivel 5 alrededor de ti." },
  druidcraft: { label: "Druidismo", detail: "efecto natural menor; predice clima, hace brotar o altera sensaciones naturales." },
  "produce-flame": { label: "Producir llama", detail: "crea llama en la mano; ataque de conjuro, 2d8 fuego a nivel 5." },
  shillelagh: { label: "Shillelagh", detail: "bastón/garrote usa Sabiduría para ataque y daño; daño 1d8." },
  "thorn-whip": { label: "Látigo de espinas", detail: "ataque de conjuro; 2d6 perforante a nivel 5; atrae 10 pies si es Grande o menor." },

  bane: { label: "Perdicion", detail: "concentración; resta 1d4 a ataques y salvaciones." },
  bless: { label: "Bendecir", detail: "concentración; suma 1d4 a ataques y salvaciones.", higherLevel: "+1 objetivo por cada nivel de espacio sobre 1." },
  command: { label: "Orden imperiosa", detail: "salvación SAB; una orden breve." },
  "compelled-duel": { label: "Duelo obligado", detail: "concentración; salvación SAB; fuerza a un enemigo a centrarse en ti." },
  "create-or-destroy-water": { label: "Crear o destruir agua", detail: "crea o destruye agua; utilitario." },
  "cure-wounds": { label: "Curar heridas", detail: "toque; cura 2d8 + aptitud mágica.", higherLevel: "+2d8 de curación por cada nivel de espacio sobre 1." },
  "detect-evil-and-good": { label: "Detectar el mal y el bien", detail: "concentración; detecta criaturas/zonas sobrenaturales." },
  "detect-poison-and-disease": { label: "Detectar veneno y enfermedad", detail: "concentración, ritual; detecta venenos, enfermedades y criaturas infectadas." },
  "guiding-bolt": { label: "Rayo guiador", detail: "ataque de conjuro; 4d6 radiante; ventaja al próximo ataque contra el objetivo." },
  "divine-favor": { label: "Favor divino", detail: "acción adicional; tus ataques con arma hacen +1d4 radiante." },
  "divine-smite": { label: "Castigo divino", detail: "acción adicional tras impactar; +2d8 radiante, +1d8 contra infernal o no muerto." },
  "healing-word": { label: "Palabra sanadora", detail: "acción adicional; cura 2d4 + aptitud mágica a 60 pies.", higherLevel: "+2d4 de curación por cada nivel de espacio sobre 1." },
  "inflict-wounds": { label: "Infligir heridas", detail: "salvación CON; 2d10 necrótico." },
  "protection-from-evil-and-good": { label: "Protección contra el mal y el bien", detail: "concentración; protege contra aberraciones, celestiales, feéricos, infernales, elementales y no muertos." },
  "purify-food-and-drink": { label: "Purificar comida y bebida", detail: "ritual; purifica alimento y bebida." },
  sanctuary: { label: "Santuario", detail: "salvación SAB para atacar al protegido." },
  "shield-of-faith": { label: "Escudo de fe", detail: "concentración; +2 CA." },
  "searing-smite": { label: "Castigo abrasador", detail: "acción adicional tras impactar; daño fuego y puede seguir ardiendo." },
  "thunderous-smite": { label: "Castigo atronador", detail: "acción adicional tras impactar; daño trueno y empuja/derriba." },
  "wrathful-smite": { label: "Castigo colerico", detail: "acción adicional tras impactar; daño necrótico y puede Asustar." },
  "burning-hands": { label: "Manos ardientes", detail: "salvación DES; 3d6 fuego; cono 15 pies.", higherLevel: "+1d6 fuego por cada nivel de espacio sobre 1." },
  "charm-person": { label: "Hechizar persona", detail: "salvación SAB; humanoide queda hechizado." },
  "chromatic-orb": { label: "Orbe cromatico", detail: "ataque de conjuro; 3d8 Ácido/frío/fuego/relámpago/trueno/veneno." },
  "color-spray": { label: "Rociada de color", detail: "cono 15 pies.; ciega criaturas afectadas." },
  "detect-magic": { label: "Detectar magia", detail: "concentración, ritual; detecta magia 30 pies." },
  "disguise-self": { label: "Disfrazarse", detail: "cambia tu apariencia 1 hora." },
  "false-life": { label: "Vida falsa", detail: "gana 2d4 + 4 PG temporales.", higherLevel: "+5 PG temporales por cada nivel de espacio sobre 1." },
  "feather-fall": { label: "Caída de pluma", detail: "reacción; hasta 5 criaturas caen lento." },
  "find-familiar": { label: "Encontrar familiar", detail: "ritual; invoca familiar." },
  "fog-cloud": { label: "Nube de niebla", detail: "concentración; área oscurecida." },
  grease: { label: "Grasa", detail: "salvación DES; área difícil y caídas." },
  entangle: { label: "Enredar", detail: "concentración; terreno difícil, salvación FUE o queda Restringido." },
  goodberry: { label: "Bayas buenas", detail: "crea 10 bayas; cada una cura 1 PG y alimenta por un día." },
  "ice-knife": { label: "Cuchillo de hielo", detail: "ataque de conjuro 1d10 perforante; explota 2d6 frío, salvación DES." },
  identify: { label: "Identificar", detail: "ritual; identifica propiedades mágicas." },
  jump: { label: "Saltar", detail: "aumenta distancia de salto." },
  "mage-armor": { label: "Armadura de mago", detail: "CA base 13 + DES; dura 8 h." },
  "magic-missile": { label: "Proyectil mágico", detail: "3 dardos; cada uno 1d4 + 1 fuerza; impacta automatico.", higherLevel: "+1 dardo por cada nivel de espacio sobre 1." },
  "ray-of-sickness": { label: "Rayo nauseabundo", detail: "ataque de conjuro; 2d8 veneno y salvación CON contra envenenado." },
  shield: { label: "Escudo", detail: "reacción; +5 CA hasta tu próximo turno; bloquea Proyectil mágico" },
  "shield-spell": { label: "Escudo", detail: "reacción; +5 CA hasta tu próximo turno; bloquea Proyectil mágico" },
  "silent-image": { label: "Imagen silenciosa", detail: "concentración; ilusión visual." },
  sleep: { label: "Dormir", detail: "concentración; afecta criaturas según PG." },
  "tashas-hideous-laughter": { label: "Risa horrible de Tasha", detail: "salvación SAB; objetivo cae incapacitado y tumbado." },
  "thunderwave": { label: "Onda atronadora", detail: "salvación CON; 2d8 trueno y empuja 10 pies.; cubo 15 pies.", higherLevel: "+1d8 trueno por cada nivel de espacio sobre 1." },
  "witch-bolt": { label: "Rayo de bruja", detail: "ataque de conjuro; 2d12 relámpago, concentración." },

  "arcane-vigor": { label: "Vigor arcano", detail: "recupera PG usando dados disponibles del conjuro." },
  aid: { label: "Ayuda", detail: "aumenta PG maximos y actuales de aliados.", higherLevel: "+5 PG por cada nivel de espacio sobre 2." },
  augury: { label: "Augurio", detail: "ritual; presagio sobre un curso de acción." },
  "arcane-lock": { label: "Cerradura arcana", detail: "bloquea magicamente una puerta, cofre o entrada." },
  barkskin: { label: "Piel robliza", detail: "CA mínima 17 del objetivo mientras dure." },
  "beast-sense": { label: "Sentidos de bestia", detail: "concentración, ritual; percibes mediante una bestia voluntaria." },
  "blindness-deafness": { label: "Ceguera/Sordera", detail: "salvación CON; ciega o ensordece." },
  "calm-emotions": { label: "Calmar emociones", detail: "concentración; suprime encanto/miedo u hostilidad." },
  blur: { label: "Desenfocar", detail: "concentración; ataques contra ti tienen desventaja." },
  "cloud-of-daggers": { label: "Nube de dagas", detail: "concentración; 4d4 cortante en cubo 5 pies.", higherLevel: "+2d4 cortante por cada nivel de espacio sobre 2." },
  "continual-flame": { label: "Llama continua", detail: "crea una llama mágica que ilumina y no consume combustible." },
  darkness: { label: "Oscuridad", detail: "concentración; oscuridad mágica." },
  darkvision: { label: "Visión en la oscuridad", detail: "otorga visión en la oscuridad 60 pies." },
  "detect-thoughts": { label: "Detectar pensamientos", detail: "concentración; lee pensamientos superficiales." },
  "dragons-breath": { label: "Aliento de dragon", detail: "concentración; acción para cono 15 pies.; 3d6 tipo elegido.", higherLevel: "+1d6 por cada nivel de espacio sobre 2." },
  "enhance-ability": { label: "Mejorar característica", detail: "concentración; ventaja en pruebas de un atributo y beneficio menor." },
  "enlarge-reduce": { label: "Agrandar/Reducir", detail: "concentración; cambia tamaño, daño y pruebas de Fuerza." },
  "find-traps": { label: "Encontrar trampas", detail: "detecta trampas dentro del alcance." },
  "flame-blade": { label: "Hoja flamigera", detail: "concentración; ataque de conjuro cuerpo a cuerpo, 3d6 fuego." },
  "flaming-sphere": { label: "Esfera flamigera", detail: "concentración; 2d6 fuego, salvación DES." },
  "gentle-repose": { label: "Dulce descanso", detail: "ritual; preserva un cadaver." },
  "hold-person": { label: "Inmovilizar persona", detail: "salvación SAB; paraliza humanoide.", higherLevel: "+1 objetivo por cada nivel de espacio sobre 2." },
  "homunculus-servant": { label: "Servidor homunculo", detail: "ritual; crea servidor constructo con gema o cristal de 100+ PO." },
  "lesser-restoration": { label: "Restauración menor", detail: "termina una enfermedad o condición específica." },
  invisibility: { label: "Invisibilidad", detail: "concentración; objetivo invisible." },
  levitate: { label: "Levitar", detail: "concentración; criatura u objeto sube o baja verticalmente." },
  "locate-object": { label: "Localizar objeto", detail: "concentración; detecta dirección de un objeto." },
  "magic-weapon": { label: "Arma mágica", detail: "vuelve mágica un arma y mejora ataque/daño." },
  "melfs-acid-arrow": { label: "Flecha acida de Melf", detail: "ataque de conjuro; 4d4 Ácido y 2d4 Ácido posterior." },
  "mirror-image": { label: "Imagen multiple", detail: "crea duplicados defensivos; no requiere concentración." },
  "misty-step": { label: "Paso brumoso", detail: "acción adicional; teletransporte 30 pies" },
  moonbeam: { label: "Rayo lunar", detail: "concentración; salvación CON, 2d10 radiante en cilindro 5 pies." },
  "protection-from-poison": { label: "Protección contra veneno", detail: "neutraliza veneno o da resistencia y ventaja contra veneno." },
  "find-steed": { label: "Encontrar montura", detail: "invoca montura sobrenatural aliada; dura hasta desaparecer o morir." },
  "scorching-ray": { label: "Rayo abrasador", detail: "3 ataques de conjuro; cada rayo 2d6 fuego.", higherLevel: "+1 rayo por cada nivel de espacio sobre 2." },
  shatter: { label: "Estallar", detail: "salvación CON; 3d8 trueno; esfera 10 pies.", higherLevel: "+1d8 trueno por cada nivel de espacio sobre 2." },
  silence: { label: "Silencio", detail: "concentración, ritual; zona sin sonido." },
  "spike-growth": { label: "Crecimiento de espinas", detail: "concentración; terreno difícil oculto, 2d4 perforante por cada 5 pies movidos." },
  "spider-climb": { label: "Trepar cual arana", detail: "concentración; trepa paredes y techos con manos libres." },
  "spiritual-weapon": { label: "Arma espiritual", detail: "concentración; ataque de conjuro con arma flotante." },
  "shining-smite": { label: "Castigo brillante", detail: "concentración; acción adicional tras impactar; el objetivo brilla y recibe daño radiante." },
  suggestion: { label: "Sugestion", detail: "salvación SAB; orden razonable, concentración." },
  "summon-beast": { label: "Convocar bestia", detail: "concentración; invoca espiritu bestial que lucha contigo." },
  "warding-bond": { label: "Vínculo protector", detail: "+1 CA/salvaciones y resistencia; compartes daño." },
  web: { label: "Telaraña", detail: "concentración; terreno difícil y restricción, salvación DES." },
  "zone-of-truth": { label: "Zona de verdad", detail: "salvación CAR; impide mentir dentro del área." },
  "arms-of-hadar": { label: "Brazos de Hadar", detail: "salvación FUE; 2d6 necrótico y sin reacciones." },
  alarm: { label: "Alarma", detail: "ritual; protege zona y avisa si entra una criatura." },
  "armor-of-agathys": { label: "Armadura de Agathys", detail: "5 PG temporales por nivel de espacio; quien te golpea cuerpo a cuerpo recibe frío." },
  "hellish-rebuke": { label: "Represalia infernal", detail: "reacción; salvación DES; 2d10 fuego.", higherLevel: "+1d10 fuego por cada nivel de espacio sobre 1." },
  hex: { label: "Maleficio", detail: "concentración; +1d6 necrótico al golpear al objetivo y penaliza una habilidad." },
  enthrall: { label: "Fascinar", detail: "concentración; criaturas tienen desventaja para percibir a otros." },
  "ray-of-enfeeblement": { label: "Rayo debilitador", detail: "ataque de conjuro; objetivo hace la mitad de daño con ataques de Fuerza, concentración." },
  "hunger-of-hadar": { label: "Hambre de Hadar", detail: "concentración; oscuridad y daño frío/ácido en área." },

  "animate-dead": { label: "Animar muertos", detail: "crea o mantiene un servidor no muerto." },
  "aura-of-vitality": { label: "Aura de vitalidad", detail: "concentración; acción adicional para curar dentro del aura." },
  "beacon-of-hope": { label: "Faro de esperanza", detail: "concentración; ventaja contra miedo/muerte y curación máxima." },
  "bestow-curse": { label: "Lanzar maldición", detail: "concentración; impone maldición a un objetivo." },
  clairvoyance: { label: "Clarividencia", detail: "concentración; sensor invisible a distancia." },
  "call-lightning": { label: "Llamar relámpagos", detail: "concentración; salvación DES, 3d10 relámpago desde nube de tormenta." },
  "conjure-animals": { label: "Conjurar animales", detail: "concentración; convoca espiritus bestiales para combatir." },
  "create-food-and-water": { label: "Crear comida y agua", detail: "crea alimento y agua para el grupo." },
  counterspell: { label: "Contrahechizo", detail: "reacción; intenta interrumpir un conjuro." },
  daylight: { label: "Luz del día", detail: "luz brillante amplia; puede disipar oscuridad mágica." },
  "dispel-magic": { label: "Disipar magia", detail: "termina efectos mágicos de nivel 3 o inferior; prueba si superior." },
  "elemental-weapon": { label: "Arma elemental", detail: "concentración; arma mágica con +1 al ataque y 1d4 daño elemental." },
  "feign-death": { label: "Simular muerte", detail: "ritual; objetivo parece muerto y queda protegido." },
  fireball: { label: "Bola de fuego", detail: "salvación DES; 8d6 fuego; esfera 20 pies." },
  fly: { label: "Volar", detail: "concentración; velocidad vuelo 60 pies." },
  haste: { label: "Prisa", detail: "concentración; +2 CA, ventaja DES, acción extra limitada." },
  "hypnotic-pattern": { label: "Patron hipnotico", detail: "salvación SAB; incapacita en cubo 30 pies., concentración." },
  "magic-circle": { label: "Círculo mágico", detail: "protege o encierra criaturas sobrenaturales." },
  "mass-healing-word": { label: "Palabra sanadora en masa", detail: "acción adicional; cura varias criaturas." },
  "gaseous-form": { label: "Forma gaseosa", detail: "concentración; objetivo se vuelve nube, vuela lento y resiste daño." },
  blink: { label: "Intermitencia", detail: "puedes desaparecer al Plano Etereo al final de tus turnos." },
  "eldritch-blast": { label: "Explosión sobrenatural", detail: "ataque de conjuro; 2 rayos a nivel 5, cada uno 1d10 fuerza." },
  "meld-into-stone": { label: "Fundirse con la piedra", detail: "ritual; entras en piedra." },
  nondetection: { label: "Indetectable", detail: "oculta contra adivinacion." },
  "pass-without-trace": { label: "Pasar sin dejar rastro", detail: "concentración; +10 Sigilo al grupo." },
  "protection-from-energy": { label: "Protección contra energía", detail: "concentración; resistencia a un tipo elemental." },
  "remove-curse": { label: "Quitar maldición", detail: "termina maldición sobre criatura u objeto." },
  revivify: { label: "Revivir", detail: "revive criatura muerta recientemente." },
  sending: { label: "Recado", detail: "mensaje breve a cualquier distancia." },
  "sleet-storm": { label: "Tormenta de aguanieve", detail: "concentración; área helada y muy obstruida, afecta concentración y caídas." },
  "lightning-bolt": { label: "Relámpago", detail: "salvación DES; 8d6 relámpago; línea 100 pies." },
  slow: { label: "Ralentizar", detail: "salvación SAB; reduce acciones, CA y velocidad, concentración." },
  "speak-with-dead": { label: "Hablar con los muertos", detail: "preguntas a un cadaver." },
  "spirit-guardians": { label: "Guardianes espirituales", detail: "concentración; área alrededor de ti, daño radiante/necrótico y ralentiza." },
  "stinking-cloud": { label: "Nube apestosa", detail: "salvación CON; pierde acción dentro del área, concentración." },
  "summon-fey": { label: "Convocar hada", detail: "concentración; invoca espiritu feérico." },
  "summon-undead": { label: "Convocar muerto viviente", detail: "concentración; invoca espiritu no muerto." },
  tongues: { label: "Lenguas", detail: "entiende y habla cualquier idioma." },
  "vampiric-touch": { label: "Toque vampirico", detail: "ataque de conjuro; 3d6 necrótico y te curas la mitad." },
  "water-breathing": { label: "Respirar bajo el agua", detail: "ritual; hasta 10 criaturas respiran bajo el agua." },
  "water-walk": { label: "Caminar sobre el agua", detail: "ritual; camina sobre liquidos." },
  "wind-wall": { label: "Muro de viento", detail: "concentración; muro que bloquea proyectiles y causa 3d8 contundente." },
  "starry-wisp": { label: "Brizna estelar", detail: "ataque de conjuro; 2d8 radiante a nivel 5; el objetivo brilla." },
  "vicious-mockery": { label: "Burla cruel", detail: "salvación SAB; 2d6 psíquico a nivel 5; desventaja al próximo ataque." },
  "animal-friendship": { label: "Amistad animal", detail: "salvación SAB; bestia queda encantada." },
  "ensnaring-strike": { label: "Golpe atrapador", detail: "concentración; ataque con arma enreda, salvación FUE o Restringido." },
  "hail-of-thorns": { label: "Lluvia de espinas", detail: "acción adicional tras impactar con arma a distancia; salvación DES, daño perforante en área." },
  "comprehend-languages": { label: "Comprender idiomas", detail: "ritual; entiendes idiomas por 1 hora." },
  "dissonant-whispers": { label: "Susurros disonantes", detail: "salvación SAB; 3d6 psíquico y el objetivo usa reacción para alejarse." },
  "faerie-fire": { label: "Fuego feérico", detail: "concentración; revela objetivos y da ventaja a ataques contra ellos." },
  heroism: { label: "Heroísmo", detail: "concentración; inmune a Asustado y gana PG temporales cada turno." },
  longstrider: { label: "Zancada prodigiosa", detail: "aumenta velocidad 10 pies." },
  "speak-with-animals": { label: "Hablar con animales", detail: "ritual; comunicate con bestias." },
  "unseen-servant": { label: "Sirviente invisible", detail: "ritual; servidor invisible para tareas simples." },
  "animal-messenger": { label: "Mensajero animal", detail: "ritual; envia un mensaje mediante una bestia pequeña." },
  enthrall: { label: "Fascinar", detail: "concentración; distrae criaturas con tu actuacion." },
  "heat-metal": { label: "Calentar metal", detail: "concentración; 2d8 fuego a metal y posible desventaja." },
  "hunters-mark": { label: "Marca del cazador", detail: "concentración; acción adicional; +1d6 daño al objetivo marcado." },
  "cordon-of-arrows": { label: "Cordón de flechas", detail: "preparas munición mágica; criaturas cercanas activan salvación DES o reciben daño." },
  "gust-of-wind": { label: "Ráfaga de viento", detail: "concentración; línea de viento que empuja, dificulta movimiento y dispersa gases." },
  knock: { label: "Abrir", detail: "abre o desatasca una cerradura, puerta o contenedor." },
  "locate-animals-or-plants": { label: "Localizar animales o plantas", detail: "ritual; encuentra especie animal o vegetal cercana." },
  "magic-mouth": { label: "Boca mágica", detail: "ritual; mensaje mágico activado por condicion." },
  "phantasmal-force": { label: "Fuerza fantasmal", detail: "concentración; ilusión mental que puede dañar." },
  "rope-trick": { label: "Truco de cuerda", detail: "crea espacio extradimensional oculto al final de una cuerda." },
  "see-invisibility": { label: "Ver invisibilidad", detail: "ves criaturas/objetos invisibles." },
  fear: { label: "Miedo", detail: "concentración; cono 30 pies, salvación SAB o Asustado." },
  "glyph-of-warding": { label: "Glifo custodio", detail: "glifo mágico con efecto explosivo o conjuro almacenado." },
  "leomunds-tiny-hut": { label: "Cabaña diminuta de Leomund", detail: "ritual; refugio inmovil por 8 horas." },
  "major-image": { label: "Imagen mayor", detail: "concentración; ilusión visual, sonora y sensorial." },
  "plant-growth": { label: "Crecimiento vegetal", detail: "altera plantas; terreno muy difícil o mejora cosecha." },
  "speak-with-plants": { label: "Hablar con plantas", detail: "comunicate con plantas y manipula vegetacion cercana." },
};

export function getSpellSheetDetail(spellId) {
  return spellSheetDetails[spellId] || null;
}

